
[workspace]
members = [
  "ark-lib",
  "ark-testing",
  "aspd-rpc-client",
  "aspd",
  "bark",
  "bark-cln",
  "bark-json",

  "sled-utils",
  "stream-until",
]

resolver = "2"

# TODO(stevenroose) at some point probably move these inline
[workspace.dependencies]
# Rust stack
anyhow = { version = "1.0", features = ["backtrace"] }
lazy_static = "=1.4.0"
log = "0.4.20"
fern = { version = "0.6.2", features = [ "colored" ] }
hex= "=0.4.3"
clap = { version = "4.4.18", features = [ "derive" ] }
chrono = "0.4"
serde = { version = "1", feature = [ "derive" ] }
serde_json = "1"
# TODO(stevenroose) consider messagepack or so
ciborium = "0.2.1"

# bitcoin stack
bitcoin = { version = "0.32", features = [ "serde", "rand", "rand-std" ] }
bip39 = { version = "2.0.0", features = [ "rand", "serde" ] }
miniscript = "12.2"
rand = { version = "0.8.5", features = [ "std", "std_rng" ] }
# bdk = "1.0.0-alpha.3"
# bdk_electrum = "0.5.0"
# bdk_file_store = "0.3.0"
# bdk_bitcoind_rpc = "0.2.0"
bdk_wallet = { git = "https://github.com/stevenroose/bdk.git", rev = "05438017876c3338d091ca85e52242b455e2193a" }
bdk_esplora = { git = "https://github.com/stevenroose/bdk.git", rev = "05438017876c3338d091ca85e52242b455e2193a" }
bdk_file_store = { git = "https://github.com/stevenroose/bdk.git", rev = "05438017876c3338d091ca85e52242b455e2193a" }
bdk_bitcoind_rpc = { git = "https://github.com/stevenroose/bdk.git", rev = "05438017876c3338d091ca85e52242b455e2193a" }
lnurl-rs = "0.6.0"
# this one is a workaround for a bug in lnurl-rs
bitcoin030 = { package = "bitcoin", version = "0.30.2", features = [ "std" ] }

sled = "0.34.7"

# LDK-dependencies
lightning-invoice = { version = "0.32.0-rc1", features = [ "std", "serde" ] }

# async + gRPC stack
tonic = { version = "0.12.2", features = [ "tls", "tls-roots", "gzip" ] }
tonic-build = "0.12.2"
prost = "0.13.2"
tokio = { version = "1.35", features = [ "full" ] }
tokio-stream = { version = "0.1.14", features = [ "sync" ] }
futures = {version = "0.3.30"}
