[package]
name = "bark-cln"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-lib = { path = "../ark-lib" }
tonic.workspace = true
prost.workspace = true

[build-dependencies]
tonic-build.workspace= true
