[package]
name = "sled-utils"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/ark-bitcoin/bark"

[dependencies]
anyhow.workspace = true
sled.workspace = true
serde.workspace = true
ciborium.workspace = true
