
when:
  - event: pull_request
  - event: push
    branch: master

steps:
  - name: build
    image: stevenroose/bark-ci-tests
    commands:
      - cargo build --workspace
      - ls -al ./target/debug

  - name: test-unit
    image: stevenroose/bark-ci-tests
    commands:
      - cargo test --workspace --exclude ark-testing --target-dir ./target-unit

  - name: test-integration
    depends_on: build
    image: stevenroose/bark-ci-tests
    commands:
      - export ASPD_EXEC=$CI_WORKSPACE/target/debug/aspd
      - export BARK_EXEC=$CI_WORKSPACE/target/debug/bark
      - cargo test --package ark-testing

  - name: push-github-mirror
    when:
      - event: push
        branch: master
    failure: ignore
    image: appleboy/drone-git-push
    settings:
      remote: git@github.com:ark-bitcoin/bark.git
      branch: master
      local_branch: master
      force: true
      ssh_key:
        from_secret: github-mirror-push-key
